spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://host.docker.internal:5001/db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
