spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://auth-service-db:5432/db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port=4005
jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351